### ISSUE TITLE
fr.opensagres.poi.xwpf.converter.pdf.PdfConverter

### ISSUE THREAD

**Issue by farimarwat** [centic9/poi-on-android#101]
Kindly port the pdf converter as well and include it in the jar

**Comment by centic9** [comment]
This seems to be part of https://github.com/opensagres/xdocreport which is a product that is based on Apache POI, but otherwise developed independent of Apache POI itself.

I can play around with it at some point, but if you have interest, maybe you can give it a try yourself and try what happens if you add the additional dependency in a similar way than what this project already does?

**Comment by farimarwat** [comment]
This is my updated jar:
https://www.mediafire.com/file/7pc6rlpsdi4zku9/poishadow-all.jar/file

New dependencies added along with its child dependencies:
https://mvnrepository.com/artifact/fr.opensagres.xdocreport/org.apache.poi.xwpf.converter.pdf/1.0.6

Code:
 fun docx2Pdf(wordinput:InputStream, pdfoutput:OutputStream){
            try{
                val document = XWPFDocument(wordinput)
               
                val options = PdfOptions.create()
            
                PdfConverter.getInstance().convert(document, pdfoutput, options)
                Log.e(TAG,"File converted Successfully")
            }catch (ex:Exception){
                Log.e(TAG,ex.toString())
            }
        }

After runnign the app it shows below error: 

java.lang.NoClassDefFoundError: Failed resolution of: Lorg/openxmlformats/schemas/wordprocessingml/x2006/main/FontsDocument;
        at fr.opensagres.poi.xwpf.converter.core.styles.XWPFStylesDocument$FontsDocumentVisitor.visitDocumentPart(XWPFStylesDocument.java:1600)
        at fr.opensagres.poi.xwpf.converter.core.styles.XWPFStylesDocument$DocumentVisitor.visitDocument(XWPFStylesDocument.java:1496)
        at fr.opensagres.poi.xwpf.converter.core.styles.XWPFStylesDocument.getFontsDocument(XWPFStylesDocument.java:1618)
        at fr.opensagres.poi.xwpf.converter.core.styles.XWPFStylesDocument.<init>(XWPFStylesDocument.java:198)
        at fr.opensagres.poi.xwpf.converter.core.styles.XWPFStylesDocument.<init>(XWPFStylesDocument.java:192)
        at fr.opensagres.poi.xwpf.converter.core.XWPFDocumentVisitor.createStylesDocument(XWPFDocumentVisitor.java:183)
        at fr.opensagres.poi.xwpf.converter.core.XWPFDocumentVisitor.<init>(XWPFDocumentVisitor.java:176)
        at fr.opensagres.poi.xwpf.converter.pdf.internal.PdfMapper.<init>(PdfMapper.java:165)
        at fr.opensagres.poi.xwpf.converter.pdf.PdfConverter.doConvert(PdfConverter.java:56)
        at fr.opensagres.poi.xwpf.converter.pdf.PdfConverter.doConvert(PdfConverter.java:39)
        at fr.opensagres.poi.xwpf.converter.core.AbstractXWPFConverter.convert(AbstractXWPFConverter.java:42)

**Comment by centic9** [comment]
xdocreport in version 1.0.6 includes a very outdated version of Apache POI. 

May using latest "fr.opensagres.xdocreport:fr.opensagres.poi.xwpf.converter.pdf:2.0.4" will work?

**Comment by farimarwat** [comment]
Ok. Now I am working on updated package for xwpf converter:
https://jar-download.com/artifact-search/fr.opensagres.poi.xwpf.converter.pdf

I have compiled the above artifact along with its dependency + your android ported POI. Now the problem exists only in xmlbeans package:

Crash while converting:
 apache.poi.ooxml.POIXMLException: error: The 'namespace-prefix' feature is not supported while the 'namespaces' feature is enabled

So is it possible to compile this repo from source via android studio?

**Comment by centic9** [comment]
Sounds like a problem we saw with older versions of XmlBeans. Rebuilding the latest version of this project as described at https://github.com/centic9/poi-on-android#build-the-jar-yourself should help.

Note: Make sure to include the pdf-convert dependency in poishadow and not poitest to not drag in Apache POI a 2nd time.

**Comment by Tigaatman** [comment]
Have you solved this problem？
Why am I still reporting an error，Here is my configuration
    implementation files('libs/poishadow-all.jar')
    implementation('fr.opensagres.xdocreport:fr.open.poi.xwpf.converter.pdf:2.0.4'){
        exclude group: 'org.apache.poi', module: 'poi-ooxml-full'
        exclude group: 'org.apache.poi', module: 'poi-ooxml'
        exclude group: 'org.apache.xmlbeans', module: 'xmlbeans'
    }

error：java.lang.NoClassDefFoundError: Failed resolution of: Lorg/openxmlformats/schemas/wordprocessingml/x2006/main/FontsDocument;

**Comment by centic9** [comment]
As stated above you are likely better off if you include the additional lib in poishadow and rebuild that library as otherwise classloaders will not match and you will get such NoClassDefFoundError.

**Comment by centic9** [comment]
I have now successfully tried this. See https://github.com/centic9/poi-on-android/tree/docx_to_pdf_convert for the changes which make it work for me. You need to rebuild the shadow-lib to include the additional functionality properly.
