### ISSUE TITLE
Cannot insert picture in a XWPFDocument

### ISSUE THREAD

**Issue by albionb96** [centic9/poi-on-android#102]
Hi all,

I am trying for many days to insert some text and some pictures from my android app into a doxc file using apache poi xwpfdocument. Everything works okay, the text is inserted 100%, but when I try to enter an image then I see only a rectangle in the generated docx file saying that the picture can't be displayed. I tried literally everything and every solution that is out there, but I am not having success.

I tried using the standard approach as described in the documentation: https://svn.apache.org/repos/asf/poi/trunk/poi-examples/src/main/java/org/apache/poi/examples/xwpf/usermodel/SimpleImages.java

And also the solution provided here: https://bz.apache.org/bugzilla/show_bug.cgi?id=49765#c26

**Comment by centic9** [comment]
I have now updated this project to include a sample which produces a Word document, inserts a picture and then stores the resulting document in the "download" folder. See "DOCX with image" when you run the "poitest" application.

When I download the resulting file and display it, the image is properly added at the end.

So as far as I see it works for me. Make sure you check log-output of your application to capture any hidden exceptions or error-messages. Also note that I had to "inline" function `toEMU()` to avoid missing classes from `java.awt` package.
