### ISSUE TITLE
Office to pdf

### ISSUE THREAD

**Issue by DevTrinh** [centic9/poi-on-android#107]
How to convert office file to pdf, suppose I have a docx file, I want to convert it to pdf. I have tried many ways but without success, do you have any suggestions?

**Comment by centic9** [comment]
Hi, there is no such functionality available as part of Apache POI, thus this project also does not offer any support.

There are multiple related questions about this on StackOverflow, see https://stackoverflow.com/search?q=apache+poi+pdf&s=b342371a-c57f-4203-89d9-b23f14cba828 please review those and discuss further there if necessary as this is outside of what this project tries to provide.
