### ISSUE TITLE
Exception on creating Worksheet with Android 4.0.3

### ISSUE THREAD

**Issue by theo744** [centic9/poi-on-android#11]
Hi,

I'm trying to open a xlsm file, add data in it and save it. File is opened and saved from external storage.

It works fine on Android 6.0 but when I try on Android 4.0.3, it raises an ExceptionInInializeError (see attached). It happens on the line :
XSSFWorkbook wb = new XSSFWorkbook(new FileInputStream(file)); (see full file SessionDAO.java attached).

I sadly have to make it work with the device on 4.0.3 and can't update it to newer Android version.

Do you know why it raises this exception and how I could have it working ?

Thanks for your feedback,
Théo
[SessionDAO.java.txt](https://github.com/centic9/poi-on-android/files/888793/SessionDAO.java.txt)
![exception](https://cloud.githubusercontent.com/assets/23457995/24592758/2037e8ca-181c-11e7-83aa-f838672ef97a.png)

**Comment by centic9** [comment]
Please see https://github.com/centic9/poi-on-android/issues/10#issuecomment-309296305 in issue #10 where my best workaround is described. I also document this in the README now until someone comes up with a better way of doing this.
