### ISSUE TITLE
Crash when run in app

### ISSUE THREAD

**Issue by wuyuansu** [centic9/poi-on-android#111]
I download the new project, and When run it,  APP crashed and logcat shows question :

java.lang.NoSuchMethodError: No static method doPrivileged(Ljava/security/PrivilegedAction;Ljava/security/AccessControlContext;[Ljava/security/Permission;)Ljava/lang/Object; in class Ljava/security/AccessController; or its super classes (declaration of 

it seems like the permission problem, but I do not do anything. how can I solve it?  Thank you.

**Comment by centic9** [comment]
Is there any way to reproduce this?  Which version of Java are you using?

**Comment by wuyuansu** [comment]
yes, When build app the problem appears. I use Android Studio Giraffe with its jdk running from jbr17.0.6.

**Comment by centic9** [comment]
This is a regression introduced by newer Log4j, for now I reverted back to the previous version, see commit https://github.com/centic9/poi-on-android/commit/5641dd33acd3e644436aaaba6560931fee811c1b 

So the latest version should work again for you.
