### ISSUE TITLE
  java.lang.NoClassDefFoundError: Failed resolution of: Ljava/awt/geom/Rectangle2D$Doubl

### ISSUE THREAD

**Issue by dashugege** [centic9/poi-on-android#113]
hello ,my code :

    id 'com.github.johnrengelman.shadow' version '8.1.1'

   gradle : distributionUrl=https://mirrors.cloud.tencent.com/gradle/gradle-8.2-all.zip

// Relocate javax dependencies so Android does not choke
    relocate 'javax.xml.namespace', 'org.apache.poi.javax.xml.namespace'
    relocate 'javax.xml.stream', 'org.apache.poi.javax.xml.stream'
    relocate 'javax.xml.XMLConstants', 'org.apache.poi.javax.xml.XMLConstants'

    // java.awt is not available, but class Color is used in APIs in POI, therefore
    // relocate this class to another one where we can include a rewrite
    relocate 'java.awt.Color', 'org.apache.poi.java.awt.Color'
    relocate 'java.awt.geom.Dimension2D', 'org.apache.poi.java.awt.geom.Dimension2D'
    relocate 'java.awt.Dimension', 'org.apache.poi.java.awt.Dimension'
    relocate 'java.awt.image.BufferedImage', 'org.apache.poi.java.awt.image.BufferedImage'

    relocate 'javax.imageio.ImageIO', 'org.apache.poi.javax.imageio.ImageIO'
    relocate 'javax.imageio.ImageReader', 'org.apache.poi.javax.imageio.ImageReader'
    relocate 'javax.imageio.stream.ImageInputStream', 'org.apache.poi.javax.imageio.stream.ImageInputStream'
    relocate 'javax.imageio.metadata.IIOMetadata', 'org.apache.poi.javax.imageio.metadata.IIOMetadata'

run app is:   java.lang.NoClassDefFoundError: Failed resolution of: Ljava/awt/geom/Rectangle2D$Doubl

help me,thx

**Comment by dashugege** [comment]
the simple test issue 84 ,crash

**Comment by centic9** [comment]
Please see https://github.com/centic9/poi-on-android#missing-javaawt-classes

So I have to give the same answer as https://github.com/centic9/poi-on-android/issues/84#issuecomment-1868258215 , this is not supported out of the box and there are no plans to "fix" this for everything in this "sample application". 

You can try to dig into this yourself if you need it, happy to integrate polished work via PRs, the available changes in the fork might be a good starting point.
