### ISSUE TITLE
Do you have a plan for the next version?

### ISSUE THREAD

**Issue by zqingdut** [centic9/poi-on-android#114]
Do you have a plan for the next version? The last release version was about two years ago.

**Comment by centic9** [comment]
I released 0.8 now, but you can always simply build `./gradlew shadowJar` in the `poishadow` directory yourself if you would like to check the latest version.

**Comment by zqingdut** [comment]
> I released 0.8 now, but you can always simply build `./gradlew shadowJar` in the `poishadow` directory yourself if you would like to check the latest version.

Thank you very much, I know I can compile it myself, but the release version release cycle generally reflects the community activity of the project, so I want to know it.
