### ISSUE TITLE
Issue opening docx file

### ISSUE THREAD

**Issue by nickdeakin** [centic9/poi-on-android#13]
I'm trying to use the latest poishadow-all.jar (I've also tried building my own with some tweaking), and running the poitest app, which seems fine as it is creating a excel document.

This issue I'm running into is when opening an existing docx file, simply by inserting this block in the poitest DocumentListActivity.java:

        try {
            File source = new File(Environment.getExternalStorageDirectory(), "Lorum_Ipsum.docx");
            FileInputStream fis = new FileInputStream(source);
            Document document = new XWPFDocument(fis);
        } catch (Exception e) {
            Log.e("ERROR", e.getLocalizedMessage());
        }

Lorum_Ipsum.docx exists in the root of the storage directory, and can be opened by other document editing apps. I've attached it here.
[Lorem_Ipsum.docx](https://github.com/centic9/poi-on-android/files/1127309/Lorem_Ipsum.docx)

The exception I am getting from this line: "Document document = new XWPFDocument(fis);" is:

org.apache.xmlbeans.SchemaTypeLoaderException: Cannot resolve type for handle _XY_Q=space|R=space@http://www.w3.org/XML/1998/namespace (schemaorg_apache_xmlbeans.system.sF1327CCA741569E70F9CA8C9AF9B44B2.cttext7f5btype) - code 13

I can see in the proguard rules there is this line:
-keep class schemaorg_apache_xmlbeans.system.sF1327CCA741569E70F9CA8C9AF9B44B2.TypeSystemHolder

I'm not sure if another reference is missing for this.

**Comment by centic9** [comment]
Please try the latest version of this project, I tried to fix this by not excluding some files that I thought are not necessary, but in fact are required when opening documents.

The sample application now reads the document and displays content from it to show that this now works as well.

**Comment by nickdeakin** [comment]
Confirmed this is now working!

Thanks for your efforts on this project, it really helps a lot!

Nick
