### ISSUE TITLE
java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by Delphian2015** [centic9/poi-on-android#14]
Hello. We spoke with you on this thread http://apache-poi.1045710.n5.nabble.com/Android-Proguard-Apache-POI-tc5727688.html. I added in project:

        System.setProperty("org.apache.poi.javax.xml.stream.XMLInputFactory", "com.fasterxml.aalto.stax.InputFactoryImpl");
        System.setProperty("org.apache.poi.javax.xml.stream.XMLOutputFactory", "com.fasterxml.aalto.stax.OutputFactoryImpl");
        System.setProperty("org.apache.poi.javax.xml.stream.XMLEventFactory", "com.fasterxml.aalto.stax.EventFactoryImpl");

At first in MainActivity.onCreate then tried to add in IntentService onHandleIntent, but I get the error :
java.lang.NoClassDefFoundError: Failed resolution of: Ljava/awt/font/FontRenderContext;
                                                                           at org.apache.a.e.d.k.<clinit>(SourceFile:110)
                                                                           at org.apache.a.g.b.a.<init>(SourceFile:117)
                                                                           at org.apache.a.g.b.f.<init>(SourceFile:79)
                                                                           at org.apache.a.g.b.g.b(SourceFile:652)
                                                                           at org.apache.a.g.b.g.a(SourceFile:673)

**Comment by centic9** [comment]
Unfortunately, current releases of POI added more dependencies on this class, but it is not available at all on Android. I need to come up with a way to shade this one into the big jar, for now it might help to use a bit older version of POI.

**Comment by Delphian2015** [comment]
Thank you

**Comment by centic9** [comment]
I did take a closer look, unfortunately some things in POI currently really require stuff from java.awt. I can try to work around some of these Problems, but some are simply not fixable easily because they use lots of functionality from java.awt, especially things like PPTX drawing, column autosizing and some others.

**Comment by Delphian2015** [comment]
thank you for your big job. I understand this is a hard work. It means we can't use all excel features (+proguard) at current time?

**Comment by centic9** [comment]
Yes, currently it is quite limited, I plan to work some more on this, either on the POI side to use less things from java.awt or on the poi-on-android side by including some java.awt replacement classes and shading POI accordingly, but it is a timely job to work on this and I lack the time for this right now, so I cannot promise when the situation will finally improve here.

One thing that would help would be to send PRs which add more stuff to the test-application here so it is easier for me to verify if any solution actually improves things.

**Comment by hawkins-wang** [comment]
I used the above method,but i got the same error again. When i delete the "**shareduserid**" in AndroidManifest,it work.I don't know the reason.

**Comment by centic9** [comment]
The shaded jar now includes a simple version of java.awt.Font to make some of the things work, other things are likely not easily possible because Android is missing full java.awt support. Thus I am closing this one, please open new issues for things that you are still missing around java.awt.* classes so I can evaluate if it is possible to support it.
