### ISSUE TITLE
Running into classcast exceptions, new proguard lines are required to fix this

### ISSUE THREAD

**Issue by peterhav** [centic9/poi-on-android#18]
When using the proguard file of this project as input, my app crashes with the following exception:

```
Exception java.lang.ClassCastException: org.apache.xmlbeans.impl.g.au cannot be cast to org.openxmlformats.schemas.spreadsheetml.x2006.main.al
org.openxmlformats.schemas.spreadsheetml.x2006.main.impl.CTWorksheetImpl.addNewPrintOptions (CTWorksheetImpl.java)
org.apache.poi.xssf.usermodel.XSSFSheet.setPrintGridlines (XSSFSheet.java:1798
```

I ended up solving this by adding these lines to the proguard file:

```
-keep class org.openxmlformats.schemas.spreadsheetml.x2006.main** { *; }
-keep class org.openxmlformats.schemas.spreadsheetml.x2006.main.impl** { *; }
```

After this my app does no longer crashes, but the APK file is increased with approx 200kb. Adding classes such as `org.openxmlformats.schemas.spreadsheetml.x2006.main.impl.CTWorksheetImpl` to the proguard configuration does not solve the crashes.

I'm very interested in any solution to keep the APK as small as possible.

**Comment by centic9** [comment]
I tried to reproduce this by adding a call to XSSFSheet.setPrintGridlines(), but this worked fine for the sample document that is created in the test-app.

Can you post some more information about how you create/open the document and maybe you can share a document which is required to reproduce the problem?

**Comment by centic9** [comment]
Long time without answer on my question, so I am closing this for now. Please comment/reopen this with some more information if this is still a problem for you with the latest version of this project.
