### ISSUE TITLE
Android 4.4 not work :'((

### ISSUE THREAD

**Issue by tienbm** [centic9/poi-on-android#21]

**Comment by centic9** [comment]
Some of the things that the project uses require newer versions of Android, especially multi-dex as far as I remember, can you share some error-details when you try to set support-levels to 4.4?

**Comment by tienbm** [comment]
E/dalvikvm: Could not find class 'org.openxmlformats.schemas.spreadsheetml.x2006.main.CTExtensionList', referenced from method org.openxmlformats.schemas.spreadsheetml.x2006.main.impl.CTSstImpl.addNewExtLst
08-09 22:24:28.490 11915-11976/tienbm.lichhoc E/dalvikvm: Could not find class 'org.openxmlformats.schemas.spreadsheetml.x2006.main.CTExtensionList', referenced from method org.openxmlformats.schemas.spreadsheetml.x2006.main.impl.CTSstImpl.getExtLst
08-09 22:24:28.490 11915-11976/tienbm.lichhoc E/dalvikvm: Could not find class 'org.openxmlformats.schemas.spreadsheetml.x2006.main.impl.CTSstImpl$1SiList', referenced from method org.openxmlformats.schemas.spreadsheetml.x2006.main.impl.CTSstImpl.getSiList
08-09 22:24:28.490 11915-11976/tienbm.lichhoc E/dalvikvm: Could not find class 'org.openxmlformats.schemas.spreadsheetml.x2006.main.CTExtensionList', referenced from method org.openxmlformats.schemas.spreadsheetml.x2006.main.impl.CTSstImpl.setExtLst
08-09 22:24:28.520 11915-11976/tienbm.lichhoc E/dalvikvm: Could not find class 'org.openxmlformats.schemas.spreadsheetml.x2006.main.CTPhoneticRun', referenced from method org.openxmlformats.schemas.spreadsheetml.x2006.main.impl.CTRstImpl.addNewRPh
08-09 22:24:28.520 11915-11976/tienbm.lichhoc E/dalvikvm: Could not find class 'org.openxmlformats.schemas.spreadsheetml.x2006.main.impl.CTRstImpl$1RList', referenced from method org.openxmlformats.schemas.spreadsheetml.x2006.main.impl.CTRstImpl.getRList
08-09 22:24:28.520 11915-11976/tienbm.lichhoc E/dalvikvm: Could not find class 'org.openxmlformats.schemas.spreadsheetml.x2006.main.CTPhoneticRun', referenced from method org.openxmlformats.schemas.spreadsheetml.x2006.main.impl.CTRstImpl.getRPhArray
08-09 22:24:28.520 11915-11976/tienbm.lichhoc E/dalvikvm: Could not find class 'org.openxmlformats.schemas.spreadsheetml.x2006.main.CTPhoneticRun[]', referenced from method org.openxmlformats.schemas.spreadsheetml.x2006.main.impl.CTRstImpl.getRPhArray
08-09 22:24:28.530 11915-11976/tienbm.lichhoc E/dalvikvm: Could not find class 'org.openxmlformats.schemas.spreadsheetml.x2006.main.impl.CTRstImpl$1RPhList', referenced from method org.openxmlformats.schemas.spreadsheetml.x2006.main.impl.CTRstImpl.getRPhList
08-09 22:24:28.530 11915-11976/tienbm.lichhoc E/dalvikvm: Could not find class 'org.openxmlformats.schemas.spreadsheetml.x2006.main.CTPhoneticRun', referenced from method org.openxmlformats.schemas.spreadsheetml.x2006.main.impl.CTRstImpl.insertNewRPh
08-09 22:24:28.530 11915-11976/tienbm.lichhoc E/dalvikvm: Could not find class 'org.openxmlformats.schemas.spreadsheetml.x2006.main.CTPhoneticRun', referenced from method org.openxmlformats.schemas.spreadsheetml.x2006.main.impl.CTRstImpl.setRPhArray

**Comment by tienbm** [comment]
i use android 4.4.2

**Comment by centic9** [comment]
Can you to rebuild the shaded jar with the fix proposed at https://github.com/centic9/poi-on-android/issues/20#issuecomment-321907950?

**Comment by centic9** [comment]
Problems with Android 4.4 should be fixed in the latest version. 

The 2nd problem is probably because you are using functionality from the ooxml-schemas that POI itself is not using and thus is not included in the shaded jar, see http://poi.apache.org/faq.html#faq-N10025 for some information. You can either rebuild the shaded jar with the full schema-jar or include the full schema jar or only the missing classes in your own application.

The upcoming version 4.0 of POI will include some of these classes as new functionality was added in that area, so when we switch to this version most of the classes listed as missing here will be included.
