### ISSUE TITLE
java.lang.VerifyError: org/openxmlformats/schemas/wordprocessingml/x2006/main/impl/CTFtnEdnImpl

### ISSUE THREAD

**Issue by archangellcc** [centic9/poi-on-android#25]
on android 4.2
I have add
-keep class org.openxmlformats.** { *; }
-keep class org.openxmlformats.** { *; }

        System.setProperty("org.apache.poi.javax.xml.stream.XMLInputFactory", "com.fasterxml.aalto.stax.InputFactoryImpl");
        System.setProperty("org.apache.poi.javax.xml.stream.XMLOutputFactory", "com.fasterxml.aalto.stax.OutputFactoryImpl");
        System.setProperty("org.apache.poi.javax.xml.stream.XMLEventFactory", "com.fasterxml.aalto.stax.EventFactoryImpl");

Also report
 Could not find class 'org.openxmlformats.schemas.wordprocessingml.x2006.main.CTCustomXmlBlock', referenced from method org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.CTFtnEdnImpl.insertNewCustomXml
09-22 19:35:19.394 2606
.....
java.lang.VerifyError: org/openxmlformats/schemas/wordprocessingml/x2006/main/impl/CTFtnEdnImpl
.....

**Comment by centic9** [comment]
For missing classes, please try to include the full ooxml-schemas-jar as described at http://poi.apache.org/faq.html#faq-N10025, any missing classes should be added to poi-ooxml-schemas directly in Apache POI, I have updated the included classes somewhat for Apache POI 4.0.0.

**Comment by centic9** [comment]
Hopefully this is fixed since some time via updating to Apache POI 4.1.2, if not please reopen with details of how to reproduce the problem with the latest version of this project.
