### ISSUE TITLE
Error:Execution failed for task

### ISSUE THREAD

**Issue by DipakMahapurkar** [centic9/poi-on-android#28]
Hello @centic9,
Thanks For such great library.
I am integrating it in android application, At the time of build it will not giving any error, But When i run my app the below exception is getting. I am not able to run my app. Please help me. Thanks in advance.

I am using jar file and version is latest one.

Error:Execution failed for task ':app:transformClassesWithNewClassShrinkerForDebug'.
> com.android.build.gradle.shrinker.ClassLookupException: Invalid class reference: javax/xml/crypto/KeySelector

**Comment by centic9** [comment]
This indicates that you use some signing/encryption and we do not include proper shaded versions of the code currently, you can try to adjust the exclude and relocate statements in build.gradle to see if that makes it work.

**Comment by centic9** [comment]
Can you provide some sample code for what you try to do so I can try to add this to the sample project?

**Comment by centic9** [comment]
I tried to reproduce this with the included sample application but couldn't. Maybe you can use this sample app and add stuff from your app one-by-one to find out what is causing this?

**Comment by centic9** [comment]
No update in a long time, so I expect this is either solved or not an issue any more.
