### ISSUE TITLE
Not working with Instant Run Option

### ISSUE THREAD

**Issue by phantomkirby** [centic9/poi-on-android#3]
In Android Studio, the default setting is to have instant run (Preferences -> Build, Exec. & Deployment -> Instant Run) turned on. However, it seems like by adding the shadow jar file, the app cannot run on my device. It is only after I turn off the instant run feature that my app runs with the shadow jar.

Is there a way to still have instant run mode on, without breaking the build?

EDIT: Also, thanks for making this! I tried using another similar library ([here](https://github.com/andruhon/android5xlsx/)) but to my knowledge that one didn't work for all gradle build versions, and I had a app:transformClassesWithDexForDebug error with it. Yours works though (provided that I turn "instant run" off).

**Comment by phantomkirby** [comment]
```
Error:Execution failed for task ':app:transformClassesWithInstantRunForDebug'.
> java.lang.ClassNotFoundException: org.apache.poi.hpsf.WritingNotSupportedException
```

I try to solve this by building a jar that includes the above, but then I get another class not found error:

```
Error:Execution failed for task ':app:transformClassesWithInstantRunForDebug'.
> java.lang.ClassNotFoundException: com.microsoft.schemas.vml.CTShape
```

I try to build a jar that includes com.microsoft..**, and then it gives me a similar error but for a different part of poi:

```
Error:Execution failed for task ':app:transformClassesWithInstantRunForDebug'.
> java.lang.ClassNotFoundException: org.apache.xmlbeans.impl.xb.xsdschema.Group
```

It seems like this will continue on and on. And the thing is, the first error that I mentioned will not show up if I check instant run as "off", which means all the classes I've been including should be "useless"/extraneous code.

**Comment by centic9** [comment]
It seems the "Instant Run" option wants to resolve all class-dependencies during compilation, however for smaller jar-files I excluded a number of things that are usually not needed. The classes for `org.apache.xmlbeans.impl.xb` are excluded as well in the default project, did you try to include these as well to see if it allows it to work?

**Comment by phantomkirby** [comment]
After including `org.apache.xmlbeans.impl.xb` as you told me to, I get the following error:

```
Error:Execution failed for task ':app:transformClassesWithInstantRunForDebug'.
> java.lang.ClassNotFoundException: org.apache.tools.ant.types.Path$PathElement
```
In poishadow's build.gradle, I don't see org.apache.tools being excluded (i.e. I don't see `exclude 'org/apache/tools/**'` in the file), and I also don't see `org.apache.tools` in the poishadow jar file either.

**Comment by centic9** [comment]
This is a separate dependency, see http://mvnrepository.com/artifact/org.apache.poi/poi-excelant, you might be able to add it in addition to 'poi' and 'poi-ooxml'

**Comment by SUPERCILEX** [comment]
https://github.com/centic9/poi-on-android/issues/5#issuecomment-283581644 fixes this because it doesn't exclude stuff.

**Comment by centic9** [comment]
I think this is mostly outdated, not sure if "Instant Run" does work with latest Android Studio 3.0, otherwise I don't see an easy way to improve support. Please report fresh issues for anything that is still missing/not working.
