### ISSUE TITLE
Class not found

### ISSUE THREAD

**Issue by ua4ever** [centic9/poi-on-android#31]
#Class not found# 
02-24 17:04:59.072 20833-20833/com.ua4ever.ua.eocrx E/dalvikvm: Could not find class 'org.openxmlformats.schemas.wordprocessingml.x2006.main.CTBackground', referenced from method org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.CTDocumentBaseImpl.addNewBackground
02-24 17:04:59.072 20833-20833/com.ua4ever.ua.eocrx E/dalvikvm: Could not find class 'org.openxmlformats.schemas.wordprocessingml.x2006.main.CTBackground', referenced from method org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.CTDocumentBaseImpl.getBackground
02-24 17:04:59.074 20833-20833/com.ua4ever.ua.eocrx E/dalvikvm: Could not find class 'org.openxmlformats.schemas.wordprocessingml.x2006.main.CTBackground', referenced from method org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.CTDocumentBaseImpl.setBackground
02-24 17:04:59.158 20833-20833/com.ua4ever.ua.eocrx E/dalvikvm: Could not find class 'org.openxmlformats.schemas.wordprocessingml.x2006.main.CTAltChunk', referenced from method org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.CTBodyImpl.addNewAltChunk
02-24 17:04:59.160 20833-20833/com.ua4ever.ua.eocrx E/dalvikvm: Could not find class 'org.openxmlformats.schemas.wordprocessingml.x2006.main.CTCustomXmlBlock', referenced from method org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.CTBodyImpl.addNewCustomXml
02-24 17:04:59.162 20833-20833/com.ua4ever.ua.eocrx E/dalvikvm: Could not find class 'org.openxmlformats.schemas.officeDocument.x2006.math.CTOMath', referenced from method org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.CTBodyImpl.addNewOMath
02-24 17:04:59.162 20833-20833/com.ua4ever.ua.eocrx E/dalvikvm: Could not find class 'org.openxmlformats.schemas.officeDocument.x2006.math.CTOMathPara', referenced from method org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.CTBodyImpl.addNewOMathPara
02-24 17:04:59.163 20833-20833/com.ua4ever.ua.eocrx E/dalvikvm: Could not find class 'org.openxmlformats.schemas.wordprocessingml.x2006.main.CTPerm', referenced from method org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.CTBodyImpl.addNewPermEnd
02-24 17:04:59.164 20833-20833/com.ua4ever.ua.eocrx E/dalvikvm: Could not find class 'org.openxmlformats.schemas.wordprocessingml.x2006.main.CTPermStart', referenced from method org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.CTBodyImpl.addNewPermStart
02-24 17:04:59.166 20833-20833/com.ua4ever.ua.eocrx E/dalvikvm: Could not find class 'org.openxmlformats.schemas.wordprocessingml.x2006.main.CTAltChunk', referenced from method org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.CTBodyImpl.getAltChunkArray
02-24 17:04:59.166 20833-20833/com.ua4ever.ua.eocrx E/dalvikvm: Could not find class 'org.openxmlformats.schemas.wordprocessingml.x2006.main.CTAltChunk[]', referenced from method org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.CTBodyImpl.getAltChunkArray
02-24 17:04:59.167 20833-20833/com.ua4ever.ua.eocrx E/dalvikvm: Could not find class 'org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.CTBodyImpl$1AltChunkList', referenced from method org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.CTBodyImpl.getAltChunkList
02-24 17:04:59.169 20833-20833/com.ua4ever.ua.eocrx E/dalvikvm: Could not find class 'org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.CTBodyImpl$1BookmarkEndList', referenced from method org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.CTBodyImpl.getBookmarkEndList
02-24 17:04:59.170 20833-20833/com.ua4ever.ua.eocrx E/dalvikvm: Could not find class 'org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.CTBodyImpl$1BookmarkStartList', referenced from method org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.CTBodyImpl.getBookmarkStartList
02-24 17:04:59.171 20833-20833/com.ua4ever.ua.eocrx E/dalvikvm: Could not find class 'org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.CTBodyImpl$1CommentRangeEndList', referenced from method org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.CTBodyImpl.getCommentRangeEndList
02-24 17:04:59.172 20833-20833/com.ua4ever.ua.eocrx E/dalvikvm: Could not find class 'org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.CTBodyImpl$1CommentRangeStartList', referenced from method org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.CTBodyImpl.getCommentRangeStartList
02-24 17:04:59.173 20833-20833/com.ua4ever.ua.eocrx E/dalvikvm: Could not find class 'org.openxmlformats.schemas.wordprocessingml.x2006.main.CTCustomXmlBlock', referenced from method org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.CTBodyImpl.getCustomXmlArray
02-24 17:04:59.173 20833-20833/com.ua4ever.ua.eocrx E/dalvikvm: Could not find class 'org.openxmlformats.schemas.wordprocessingml.x2006.main.CTCustomXmlBlock[]', referenced from method org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.CTBodyImpl.getCustomXmlArray
02-24 17:04:59.174 20833-20833/com.ua4ever.ua.eocrx E/dalvikvm: Could not find class 'org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.CTBodyImpl$1CustomXmlDelRangeEndList', referenced from method org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.CTBodyImpl.getCustomXmlDelRangeEndList
02-24 17:04:59.175 20833-20833/com.ua4ever.ua.eocrx E/dalvikvm: Could not find class 'org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.CTBodyImpl$1CustomXmlDelRangeStartList', referenced from method org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.CTBodyImpl.getCustomXmlDelRangeStartList
02-24 17:04:59.176 20833-20833/com.ua4ever.ua.eocrx E/dalvikvm: Could not find class 'org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.CTBodyImpl$1CustomXmlInsRangeEndList', referenced from method org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.CTBodyImpl.getCustomXmlInsRangeEndList
02-24 17:04:59.177 20833-20833/com.ua4ever.ua.eocrx E/dalvikvm: Could not find class 'org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.CTBodyImpl$1CustomXmlInsRangeStartList', referenced from method org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.CTBodyImpl.getCustomXmlInsRangeStartList
02-24 17:04:59.178 20833-20833/com.ua4ever.ua.eocrx E/dalvikvm: Could not find class 'org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.CTBodyImpl$1CustomXmlList', referenced from method org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.CTBodyImpl.getCustomXmlList
02-24 17:04:59.179 20833-20833/com.ua4ever.ua.eocrx E/dalvikvm: Could not find class 'org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.CTBodyImpl$1CustomXmlMoveFromRangeEndList', referenced from method org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.CTBodyImpl.getCustomXmlMoveFromRangeEndList
02-24 17:04:59.180 20833-20833/com.ua4ever.ua.eocrx E/dalvikvm: Could not find class 'org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.CTBodyImpl$1CustomXmlMoveFromRangeStartList', referenced from method org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.CTBodyImpl.getCustomXmlMoveFromRangeStartList
02-24 17:04:59.181 20833-20833/com.ua4ever.ua.eocrx E/dalvikvm: Could not find class 'org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.CTBodyImpl$1CustomXmlMoveToRangeEndList', referenced from method org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.CTBodyImpl.getCustomXmlMoveToRangeEndList
02-24 17:04:59.183 20833-20833/com.ua4ever.ua.eocrx E/dalvikvm: Could not find class 'org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.CTBodyImpl$1CustomXmlMoveToRangeStartList', referenced from method org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.CTBodyImpl.getCustomXmlMoveToRangeStartList
02-24 17:04:59.184 20833-20833/com.ua4ever.ua.eocrx E/dalvikvm: Could not find class 'org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.CTBodyImpl$1DelList', referenced from method org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.CTBodyImpl.getDelList
02-24 17:04:59.185 20833-20833/com.ua4ever.ua.eocrx E/dalvikvm: Could not find class 'org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.CTBodyImpl$1InsList', referenced from method org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.CTBodyImpl.getInsList
02-24 17:04:59.186 20833-20833/com.ua4ever.ua.eocrx E/dalvikvm: Could not find class 'org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.CTBodyImpl$1MoveFromList', referenced from method org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.CTBodyImpl.getMoveFromList
02-24 17:04:59.188 20833-20833/com.ua4ever.ua.eocrx E/dalvikvm: Could not find class 'org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.CTBodyImpl$1MoveFromRangeEndList', referenced from method org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.CTBodyImpl.getMoveFromRangeEndList
02-24 17:04:59.189 20833-20833/com.ua4ever.ua.eocrx E/dalvikvm: Could not find class 'org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.CTBodyImpl$1MoveFromRangeStartList', referenced from method org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.CTBodyImpl.getMoveFromRangeStartList
02-24 17:04:59.191 20833-20833/com.ua4ever.ua.eocrx E/dalvikvm: Could not find class 'org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.CTBodyImpl$1MoveToList', referenced from method org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.CTBodyImpl.getMoveToList
02-24 17:04:59.191 20833-20833/com.ua4ever.ua.eocrx E/dalvikvm: Could not find class 'org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.CTBodyImpl$1MoveToRangeEndList', referenced from method org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.CTBodyImpl.getMoveToRangeEndList
02-24 17:04:59.192 20833-20833/com.ua4ever.ua.eocrx E/dalvikvm: Could not find class 'org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.CTBodyImpl$1MoveToRangeStartList', referenced from method org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.CTBodyImpl.getMoveToRangeStartList
02-24 17:04:59.193 20833-20833/com.ua4ever.ua.eocrx E/dalvikvm: Could not find class 'org.openxmlformats.schemas.officeDocument.x2006.math.CTOMath', referenced from method org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.CTBodyImpl.getOMathArray
02-24 17:04:59.194 20833-20833/com.ua4ever.ua.eocrx E/dalvikvm: Could not find class 'org.openxmlformats.schemas.officeDocument.x2006.math.CTOMath[]', referenced from method org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.CTBodyImpl.getOMathArray
02-24 17:04:59.195 20833-20833/com.ua4ever.ua.eocrx E/dalvikvm: Could not find class 'org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.CTBodyImpl$1OMathList', referenced from method org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.CTBodyImpl.getOMathList
02-24 17:04:59.196 20833-20833/com.ua4ever.ua.eocrx E/dalvikvm: Could not find class 'org.openxmlformats.schemas.officeDocument.x2006.math.CTOMathPara', referenced from method org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.CTBodyImpl.getOMathParaArray
02-24 17:04:59.197 20833-20833/com.ua4ever.ua.eocrx E/dalvikvm: Could not find class 'org.openxmlformats.schemas.officeDocument.x2006.math.CTOMathPara[]', referenced from method org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.CTBodyImpl.getOMathParaArray
02-24 17:04:59.198 20833-20833/com.ua4ever.ua.eocrx E/dalvikvm: Could not find class 'org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.CTBodyImpl$1OMathParaList', referenced from method org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.CTBodyImpl.getOMathParaList
02-24 17:04:59.199 20833-20833/com.ua4ever.ua.eocrx E/dalvikvm: Could not find class 'org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.CTBodyImpl$1PList', referenced from method org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.CTBodyImpl.getPList
02-24 17:04:59.200 20833-20833/com.ua4ever.ua.eocrx E/dalvikvm: Could not find class 'org.openxmlformats.schemas.wordprocessingml.x2006.main.CTPerm', referenced from method org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.CTBodyImpl.getPermEndArray
02-24 17:04:59.201 20833-20833/com.ua4ever.ua.eocrx E/dalvikvm: Could not find class 'org.openxmlformats.schemas.wordprocessingml.x2006.main.CTPerm[]', referenced from method org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.CTBodyImpl.getPermEndArray
02-24 17:04:59.202 20833-20833/com.ua4ever.ua.eocrx E/dalvikvm: Could not find class 'org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.CTBodyImpl$1PermEndList', referenced from method org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.CTBodyImpl.getPermEndList
02-24 17:04:59.202 20833-20833/com.ua4ever.ua.eocrx E/dalvikvm: Could not find class 'org.openxmlformats.schemas.wordprocessingml.x2006.main.CTPermStart', referenced from method org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.CTBodyImpl.getPermStartArray
02-24 17:04:59.203 20833-20833/com.ua4ever.ua.eocrx E/dalvikvm: Could not find class 'org.openxmlformats.schemas.wordprocessingml.x2006.main.CTPermStart[]', referenced from method org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.CTBodyImpl.getPermStartArray
02-24 17:04:59.204 20833-20833/com.ua4ever.ua.eocrx E/dalvikvm: Could not find class 'org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.CTBodyImpl$1PermStartList', referenced from method org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.CTBodyImpl.getPermStartList
02-24 17:04:59.205 20833-20833/com.ua4ever.ua.eocrx E/dalvikvm: Could not find class 'org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.CTBodyImpl$1ProofErrList', referenced from method org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.CTBodyImpl.getProofErrList
02-24 17:04:59.206 20833-20833/com.ua4ever.ua.eocrx E/dalvikvm: Could not find class 'org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.CTBodyImpl$1SdtList', referenced from method org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.CTBodyImpl.getSdtList
02-24 17:04:59.207 20833-20833/com.ua4ever.ua.eocrx E/dalvikvm: Could not find class 'org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.CTBodyImpl$1TblList', referenced from method org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.CTBodyImpl.getTblList
02-24 17:04:59.208 20833-20833/com.ua4ever.ua.eocrx E/dalvikvm: Could not find class 'org.openxmlformats.schemas.wordprocessingml.x2006.main.CTAltChunk', referenced from method org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.CTBodyImpl.insertNewAltChunk
02-24 17:04:59.209 20833-20833/com.ua4ever.ua.eocrx E/dalvikvm: Could not find class 'org.openxmlformats.schemas.wordprocessingml.x2006.main.CTCustomXmlBlock', referenced from method org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.CTBodyImpl.insertNewCustomXml
02-24 17:04:59.211 20833-20833/com.ua4ever.ua.eocrx E/dalvikvm: Could not find class 'org.openxmlformats.schemas.officeDocument.x2006.math.CTOMath', referenced from method org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.CTBodyImpl.insertNewOMath
02-24 17:04:59.212 20833-20833/com.ua4ever.ua.eocrx E/dalvikvm: Could not find class 'org.openxmlformats.schemas.officeDocument.x2006.math.CTOMathPara', referenced from method org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.CTBodyImpl.insertNewOMathPara
02-24 17:04:59.212 20833-20833/com.ua4ever.ua.eocrx E/dalvikvm: Could not find class 'org.openxmlformats.schemas.wordprocessingml.x2006.main.CTPerm', referenced from method org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.CTBodyImpl.insertNewPermEnd
02-24 17:04:59.213 20833-20833/com.ua4ever.ua.eocrx E/dalvikvm: Could not find class 'org.openxmlformats.schemas.wordprocessingml.x2006.main.CTPermStart', referenced from method org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.CTBodyImpl.insertNewPermStart
02-24 17:04:59.216 20833-20833/com.ua4ever.ua.eocrx E/dalvikvm: Could not find class 'org.openxmlformats.schemas.wordprocessingml.x2006.main.CTAltChunk', referenced from method org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.CTBodyImpl.setAltChunkArray
02-24 17:04:59.281 20833-20833/com.ua4ever.ua.eocrx E/AndroidRuntime: FATAL EXCEPTION: main
                                                                      java.lang.VerifyError: org/openxmlformats/schemas/wordprocessingml/x2006/main/impl/CTBodyImpl
                                                                          at java.lang.reflect.Constructor.constructNative(Native Method)
                                                                          at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
                                                                          at org.apache.xmlbeans.impl.schema.SchemaTypeImpl.createUnattachedNode(SchemaTypeImpl.java:1934)
                                                                          at org.apache.xmlbeans.impl.schema.SchemaTypeImpl.createElementType(SchemaTypeImpl.java:1051)
                                                                          at org.apache.xmlbeans.impl.values.XmlObjectBase.create_element_user(XmlObjectBase.java:938)
                                                                          at org.apache.xmlbeans.impl.store.Xobj.getUser(Xobj.java:1675)
                                                                          at org.apache.xmlbeans.impl.store.Cur.getUser(Cur.java:2659)
                                                                          at org.apache.xmlbeans.impl.store.Xobj.insertElement(Xobj.java:2117)
                                                                          at org.apache.xmlbeans.impl.store.Xobj.add_element_user(Xobj.java:2197)
                                                                          at org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.CTDocument1Impl.addNewBody(Unknown Source)
                                                                          at org.apache.poi.xwpf.usermodel.XWPFDocument.onDocumentCreate(XWPFDocument.java:271)
                                                                          at org.apache.poi.xwpf.usermodel.XWPFDocument.<init>(XWPFDocument.java:124)
                                                                          at com.ua4ever.ua.eocrx.util.DocumenterWord.exportToWord(DocumenterWord.java:75)
                                                                          at com.ua4ever.ua.eocrx.TextActivity.tombolExport(TextActivity.java:75)
                                                                          at com.ua4ever.ua.eocrx.TextActivity.onOptionsItemSelected(TextActivity.java:66)
                                                                          at android.app.Activity.onMenuItemSelected(Activity.java:2638)
                                                                          at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:408)
                                                                          at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:195)
                                                                          at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:113)
                                                                          at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:113)
                                                                          at android.support.v7.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:69)
                                                                          at android.support.v7.widget.Toolbar$1.onMenuItemClick(Toolbar.java:206)
                                                                          at android.support.v7.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:776)
                                                                          at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:822)
                                                                          at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:156)
                                                                          at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:969)
                                                                          at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:959)
                                                                          at android.support.v7.widget.ActionMenuView.invokeItem(ActionMenuView.java:623)
                                                                          at android.support.v7.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:154)
                                                                          at android.view.View.performClick(View.java:4212)
                                                                          at android.view.View$PerformClick.run(View.java:17485)
                                                                          at android.os.Handler.handleCallback(Handler.java:800)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:100)
                                                                          at android.os.Looper.loop(Looper.java:194)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5426)
                                                                          at java.lang.reflect.Method.invokeNative(Native Method)
                                                                          at java.lang.reflect.Method.invoke(Method.java:525)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:842)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
                                                                          at dalvik.system.NativeStart.main(Native Method)

**Comment by PockerKID** [comment]
@ua4ever There are some class in "ooxml-schemas.jar", you can add it and build your own "poishadow-all.jar".

**Comment by centic9** [comment]
Can you share some details? I.e. what did you change compared to the sample project poitest in this repository?

**Comment by centic9** [comment]
`ooxml-schemas` is quite a large jar file as it contains everything that Microsoft included in the spec. As Apache POI only uses some parts from it, poi-ooxml has a dependency on a reduced set of jars via `poi-ooxml-schemas:3.17`, which should include all the required bits from `ooxml-schemas:1.3`, but obviously misses some pieces here and there. 

So your workaround will work, but it may increase the size of the resulting jars/apks quite a bit. Would be better to only include the missing pieces, ideally by getting Apache POi to include these bits in the `poi-ooxml-schemas` jar. This can be done by adding unit-tests in Apache POi which trigger loading the relevant classes.

Maybe you can provide some sample code (ideally as unit-test) which I can add to Apache POi (I am a comitter there as well), then when this project is updated it should allow to use only the smaller jar in the future.

**Comment by PockerKID** [comment]
@centic9 Indeed, the jar file is quite big. As i said brfore, i got some error when i  export a docx file, and i just know something about this.
 The error occured when i use

>  XWPFRun.setCharacterSpacing(int twips) 

method to format the file.The error is:
 `java.lang.NoClassDefFoundError: org/openxmlformats/schemas/wordprocessingml/x2006/main/CTSignedTwipsMeasure
	at org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.CTRPrImpl.addNewSpacing(Unknown Source)
	at org.apache.poi.xwpf.usermodel.XWPFRun.setCharacterSpacing(XWPFRun.java:650)`

and you can get the error use like this:

        try {
            final String filePath = Environment.getExternalStorageDirectory().getAbsolutePath() + "\Test.docx";
            final XWPFDocument docx = new XWPFDocument();
            final XWPFParagraph title = docx.createParagraph();
            final XWPFRun titleRun = title.createRun();
            titleRun.setCharacterSpacing(2); 
            final File file = new File(filePath);
            if (file.exists()) {
                file.delete();
            }
            final ByteArrayOutputStream tempStream = new ByteArrayOutputStream();
            final FileOutputStream out = new FileOutputStream(filePath, false);
            docx.write(tempStream);
            out.write(tempStream.toByteArray());
            out.close();
            tempStream.close();
        } catch (Exception e) {
            e.printStackTrace();
        }

**Comment by centic9** [comment]
Unfortunately I cannot easily fix this locally because it depends on the contents of `poi-ooxml-schemas`, which is built as part of Apache POI itself. 

We have pushed a change to Apache POi so that the missing classes are included in the next release (likely 4.0.0), for now a workaround is to use the full schemas-jar or to include the missing classes `CTSignedTwipsMeasure.class` `impl/CTSignedTwipsMeasureImpl.class` and `CTSignedTwipsMeasure$Factory.class` from the full jar in your application for now.

@ua4ever I can only include your missing classes if you can provide a small code-snippet which reproduces the problem. For now you should also be able to work around the problem by including the full jar-file as described in my previous comment.
