### ISSUE TITLE
Unable to build poishadow-all.jar

### ISSUE THREAD

**Issue by akash55** [centic9/poi-on-android#38]
Duplicate zip entry [43.jar:org/apache/poi/sl/draw/DrawNotImplemented.class]

**Comment by centic9** [comment]
Sorry but this is not a lot of info, can you provide more? E.g. steps to reproduce?

**Comment by akash55** [comment]
My project is multi-dex enabled.
when I try to build the project. It shows error: 
Duplicate zip entry [43.jar:org/apache/poi/sl/draw/DrawNotImplemented.class]
how to exclude this class from dex?

**Comment by centic9** [comment]
Do you somehow include the POI-code multiple times?

What other build-differences compared to how this project builds the jar are in your project?

**Comment by akash55** [comment]
No, I included only poishadow-all.jar in project libs folder.

Error:Execution failed for task ':app:transformClassesWithMultidexlistForDebug'.
> java.io.IOException: Can't write [D:\Android Apps\MyApplications\Demo\app\build\intermediates\multi-dex\debug\componentClasses.jar] (Can't read [D:\Android Apps\MyApplications\Demo\app\build\intermediates\transforms\desugar\debug\44.jar(;;;;;;**.class)] (Duplicate zip entry [44.jar:org/apache/poi/sl/draw/DrawNotImplemented.class]))
