### ISSUE TITLE
Transform output file poishadow\build\libs\poishadow-all.jar does not exist.

### ISSUE THREAD

**Issue by rohitgarg29** [centic9/poi-on-android#40]
Hi @centic9 ,

I am trying to build the sample project but I am getting the below error while running the application on my device. 

transfer output file poishadow\build\libs\poishadow-all.jar does not exist.

Thanks in advance.
Rohit

**Comment by rohitgarg29** [comment]
Hi,

i think that the poishadow.jar does not exist, that's why it is throwing this kind of error.

**Comment by ZCHWorld** [comment]
This is because the "poishadow" module is not referenced in the project "poitest", but "../poishadow/build/libs/poishadow-all.jar" is referenced. When you build "poitest", it will look for "poishadow-all.jar", but will not let the initiative build the "poishadow" module. Therefore, you need to manually implementation the module "poishadow" in the "poitest" in the "project structure", and then rebuild the project, then the module "poishadow" will generate the jar.

**Comment by JakeWoki** [comment]
implementation project(':poishadow')

```
Duplicate class org.apache.xmlbeans.xml.stream.Location found in modules xmlbeans-2.6.0.jar (org.apache.xmlbeans:xmlbeans:2.6.0) and xmlbeans-2.6.0.jar (org.apache.xmlbeans:xmlbeans:2.6.0)
Duplicate class org.apache.xmlbeans.xml.stream.ReferenceResolver found in modules xmlbeans-2.6.0.jar (org.apache.xmlbeans:xmlbeans:2.6.0) and xmlbeans-2.6.0.jar (org.apache.xmlbeans:xmlbeans:2.6.0)
Duplicate class org.apache.xmlbeans.xml.stream.XMLEvent found in modules xmlbeans-2.6.0.jar (org.apache.xmlbeans:xmlbeans:2.6.0) and xmlbeans-2.6.0.jar (org.apache.xmlbeans:xmlbeans:2.6.0)
Duplicate class org.apache.xmlbeans.xml.stream.XMLInputStream found in modules xmlbeans-2.6.0.jar (org.apache.xmlbeans:xmlbeans:2.6.0) and xmlbeans-2.6.0.jar (org.apache.xmlbeans:xmlbeans:2.6.0)
Duplicate class org.apache.xmlbeans.xml.stream.XMLName found in modules xmlbeans-2.6.0.jar (org.apache.xmlbeans:xmlbeans:2.6.0) and xmlbeans-2.6.0.jar (org.apache.xmlbeans:xmlbeans:2.6.0)
Duplicate class org.apache.xmlbeans.xml.stream.XMLStreamException found in modules xmlbeans-2.6.0.jar (org.apache.xmlbeans:xmlbeans:2.6.0) and xmlbeans-2.6.0.jar (org.apache.xmlbeans:xmlbeans:2.6.0)
Duplicate class org.apache.xmlbeans.xml.stream.utils.NestedThrowable found in modules xmlbeans-2.6.0.jar (org.apache.xmlbeans:xmlbeans:2.6.0) and xmlbeans-2.6.0.jar (org.apache.xmlbeans:xmlbeans:2.6.0)
Duplicate class org.apache.xmlbeans.xml.stream.utils.NestedThrowable$Util found in modules xmlbeans-2.6.0.jar (org.apache.xmlbeans:xmlbeans:2.6.0) and xmlbeans-2.6.0.jar (org.apache.xmlbeans:xmlbeans:2.6.0)
```

**Comment by ZCHWorld** [comment]
It's been a long time. At that time, God and I knew. Now only God knows.

But I can offer you some ideas:

Premise, I want to use POI to decrypt office documents on Android, and I succeed.

To solve duplicate class, I changed the package name of POI.

You can refer to the code that I left at that time. I have transferred it to githun at https://github.com/zchworld/poi-on-android.git

**Comment by centic9** [comment]
I believe we added some missing build-dependency for poitest -> poishadow in the meantime and thus this should not occur any more. 
Please reopen if you still encounter this problem with the latest version of poi-on-android
