### ISSUE TITLE
CellStyle Does Not Works On Android

### ISSUE THREAD

**Issue by inaseem** [centic9/poi-on-android#42]
The CellStyle Class Internally Uses java.awt.Color Class To Apply Styles To Cell. So This Creates An Exception In Android POI Usage. Is There Any Fix Or Work Around To Tackle This?

**Comment by LePat** [comment]
Hi,

java.awt classes have to be reimplemented to offer all fonctionnalities of apache poi to Android. By now only colors are available. On my fork I added the column autosize for my personal use. The work around will consist on some lines of java ;)

**Comment by naseemali925** [comment]
That Means CellStyle Is Not Fully Supported. Right?
I Included The Gradle Dependency From mvnrepositories And That Doesn't Have Colors Implemented Via CellStyle For Android. (It Works Perfectly Well On Other Platforms. I Checked On Windows)
CellStyle cs = wb.createCellStyle();
The Above Line Generates An Exception Pointing To The Usage Of java.awt.Color.
Did You Create A Custom Build Of The POI Library?

**Comment by centic9** [comment]
There is a workaround in place for some time already for java.awt.Color which should make it work. However there are still many other java.awt classes that might be missing when using some parts of Apache POI, unfortunately I could not find a good AWT-reimplementation for Android.

Please try the latest version and report any remaining issues.
