### ISSUE TITLE
CTPageMar not found

### ISSUE THREAD

**Issue by lh414035210** [centic9/poi-on-android#65]
![image](https://user-images.githubusercontent.com/24253339/64242089-7e434700-cf37-11e9-8a51-cb20e8176ffd.png)

use your jar ,I found CTPageMar not found,   how do I  ？

**Comment by centic9** [comment]
Unfortunately this class seems to be not included in the reduced poi-ooxml-schemas jar of Apache POI as it is not used by POi directly in that version. 

See http://poi.apache.org/components/index.html and look for "poi-ooxml-schemas" for some additional information about this.

I don't know enough about Android development and Jar-packaging to say how you can get this class included, but you likely need to rebuild the shaded jar with the missing classes included from the full "ooxml-schemas" jar.

**Comment by lh414035210** [comment]
Thank you for your reply.

**Comment by centic9** [comment]
Closing for now, will be fixed when this project can upgrade to Apache POI 4.x, however unfortunately every attempt so far failed with some strange Android related problem, so I am a bit stuck there unless someone with more knowledge than me can step in and fix this.
