### ISSUE TITLE
How can we remove some of the classes from poishadow-all.jar ?

### ISSUE THREAD

**Issue by vikash9899** [centic9/poi-on-android#67]
I am facing some duplicate class error while using it with ooxml-schemas-1.4.jar. So I want to remove some of the class from poishadow-all.jar.
Please Suggest me that how can I solve this problem.

**Comment by pbnjay** [comment]
For me it was a duplicate `org.apache.commons.collections4` package, so I did this at the command line:

    $ zip -d poishadow-all.jar org/apache/commons/collections4 

If you're on windows I don't know how, but just open the jar/zip and delete all the class files that are conflicting.

**Comment by centic9** [comment]
You should be able to add something like this to the "shadowJar" section in poishadow/build.gradle and rebuild shadowJar:

    exclude 'org/apache/commons/collections4/**'
