### ISSUE TITLE
XLSX Files, Provider com.bea.xml.stream.EventFactory not found

### ISSUE THREAD

**Issue by SteveRogers1974** [centic9/poi-on-android#69]
My simple code:

`InputStream myInput;`
            `// initialize asset manager`
            `AssetManager assetManager = getAssets();`
            `//  open excel sheet`
            `InputStream fin = openFileInput("myexcelsheet.xlsx");`
            `// Create a workbook using the File System`
            `XSSFWorkbook myWorkBook = new XSSFWorkbook(fin);`

Produces Provider com.bea.xml.stream.EventFactory not found

**Comment by centic9** [comment]
Please read the main-page/README, especially the section "Necessary System-Properties".

**Comment by SteveRogers1974** [comment]
Many thanks...

Il giorno sab 26 ott 2019 alle 21:31 Dominik Stadler <
notifications@github.com> ha scritto:
