### ISSUE TITLE
Cannot create XWPFTable in XWPFDocument document

### ISSUE THREAD

**Issue by AlexDundar** [centic9/poi-on-android#73]
Hello, I make `Android` application with possibility to create `docx` file with text and table in it. For creating a file with table I use the next code:
```
 val fileOutPutStream =
                FileOutputStream(File(Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS).path + "/mytable.docx"))

            val document = XWPFDocument()
            val tableOne = document.createTable(2, 2)
            tableOne.getRow(0).getCell(0).text = "1"
            tableOne.getRow(0).getCell(1).text = "2"
            tableOne.getRow(1).getCell(0).text = "3"
            tableOne.getRow(1).getCell(1).text = "4"

            document.write(fileOutPutStream)
            fileOutPutStream.close()
            document.close()
```

And file is created well. But when I open it, I see only texts without tables. Here is screenshot of document:

![1](https://user-images.githubusercontent.com/16223018/73928780-5ab46c00-48dc-11ea-85a8-77a33f7f840a.png)

What I make wrong? How to fix this? Thanks.

**Comment by centic9** [comment]
Does it work if you do the same with a normal Java application on a PC? Because this sounds like a problem of Apache POI itself, so you might be better off reporting the problem there if this is still an issue.

**Comment by centic9** [comment]
No response for a long time so closing this one for now, please reopen with more information if this is still an issue for you.
