### ISSUE TITLE
Error in jar file

### ISSUE THREAD

**Issue by sneha3799** [centic9/poi-on-android#79]
C:\Users\User\AndroidStudioProjects\poi-on-android\poishadow\build\libs\poishadow-all.jar

I'm getting this error. How to solve it?

**Comment by centic9** [comment]
What is the error message? You just posted a path-name...

**Comment by sneha3799** [comment]
That's the only message getting displayed.

**Comment by centic9** [comment]
Soory, but there is no way to help with only this little information. This is not even an actual error message and you did not describe anything at all here, how do expect anyone to be able to help here?

**Comment by sneha3799** [comment]
Only this message is getting displayed on android studio. That's why I'm
unable to solve it and asked you. Otherwise I would have solved myself.

Thanks anyway.

**Comment by centic9** [comment]
Sorry, but I do not see what the problem is with that little bit of information, it looks much like a project-setup issue in your IDE.

**Comment by sneha3799** [comment]
Thankyou so much. The issue is solved now. Maybe I did something wrong.

**Comment by bitamirshafiee** [comment]
Could you please tell me how did you solve it?
I try to build the project and I have the same error.
