### ISSUE TITLE
Does't support .doc and .ppt?

### ISSUE THREAD

**Issue by mrvoice** [centic9/poi-on-android#83]
Hi centic9, I try to use poi-on-android to parse doc/docx... and so on, I found that the package poishadow-all.jar supports parse files with suffix .docx/.xlsx/.pptx and .xls， but do not support .doc and .ppt. How to fix this? Just put the package poi-scratchpad-***.jar under the dir libs/ ? Waiting for your reply, thanks a lot.

**Comment by mrvoice** [comment]
Hi centic9, I try to use poi-on-android to parse doc/docx... and so on, I found that the package poishadow-all.jar supports parse files with suffix .docx/.xlsx/.pptx and .xls， but do not support .doc and .ppt. How to fix this? Just put the package poi-scratchpad-***.jar under the dir libs/ ? Waiting for your reply, thanks a lot.

**Comment by centic9** [comment]
You would add the dependency in poishadow/build.gradle and rebuild poishadow-all.jar with the additional dependency to get the classes included.

You might run into problems with too many classes, though, as Android applications seem to be quite limited in this regard.

**Comment by mrvoice** [comment]
Thank u, centic9. I've read the README again, and rebuild the pioshadow-all.jar with some new dependencies (poi & poi-scratchpad). Now it works !  🙂

**Comment by mrvoice** [comment]
The problem has been solved.

**Comment by KiruthikaAdhi** [comment]
@mrvoice can you please share the dependencies which you added. I added these two lines https://github.com/KiruthikaAdhi/poi-on-android/blob/6a549c0bbc61db3b9fe2f16a2e0db5ee7bb1e5d6/poishadow/build.gradle#L13 and https://github.com/KiruthikaAdhi/poi-on-android/blob/6a549c0bbc61db3b9fe2f16a2e0db5ee7bb1e5d6/poishadow/build.gradle#L14.
But I am facing error which trying to read a doc or ppt file.

**Comment by KiruthikaAdhi** [comment]
@mrvoice can you please share the dependencies which you added. I added these two lines https://github.com/KiruthikaAdhi/poi-on-android/blob/6a549c0bbc61db3b9fe2f16a2e0db5ee7bb1e5d6/poishadow/build.gradle#L13 and https://github.com/KiruthikaAdhi/poi-on-android/blob/6a549c0bbc61db3b9fe2f16a2e0db5ee7bb1e5d6/poishadow/build.gradle#L14.
But I am facing error which trying to read a doc or ppt file.
