### ISSUE TITLE
can't run it, NoClassDefFoundError

### ISSUE THREAD

**Issue by TOTOROYang** [centic9/poi-on-android#9]
when i run it on my phone ,the app always end of java.lang.NoClassDefFoundError.
And , can poishadow-all.jar support ppt or pptx?

**Comment by centic9** [comment]
Please provide more info, at least the full stacktrace and a code snippet of what you are trying to do.

On ppt/pptx: should work as far as POI itself has support for features, you might need to remove some excludes from the build file and rebuild the jar file if things are missing.

**Comment by centic9** [comment]
I am closing this one for now, please reopen with more information if this is still a problem for you.

**Comment by centic9** [comment]
Please see https://github.com/centic9/poi-on-android/issues/10#issuecomment-309296305 in issue #10 where a workaround is described for some type of NoClassDefError that I also document in the README now until someone comes up with a better way of doing this.
