### ISSUE TITLE
my minSdkVersion 21

### ISSUE THREAD

**Issue by luolianl** [centic9/poi-on-android#92]
MethodHandle.invoke and MethodHandle.invokeExact are only supported starting with Android O (--min-api 26)

**Comment by centic9** [comment]
The min-api 26 is currently on purpose, see https://github.com/centic9/poi-on-android#supported-android-versions 

This was needed for various problems I ran into when upgrading Apache POI to 4.x and 5.x 

I am not an expert on Android development, so I could not investigate this more and so just resorted to a higher minimum SDK level for now in the sample app.

If you manage to lower the required version by adjusting the app, a PR would be highly welcome!

**Comment by centic9** [comment]
Closing for now as I don't see a way to lower the  minSdkVersion until someone can propose a way that still works.

**Comment by gulabsagevadiya** [comment]
I have same problem as well. this is not letting us build apk out of it. there should be version check only like other libs. so can show user to use this function you need at least android 8 or higher. but in this lib forcing us to make android version higher then 26

**Comment by gulabsagevadiya** [comment]
is there any older version supported below android 8 ?

**Comment by centic9** [comment]
I could not find a way to keep older versions supported when updating to POI 5.x. 

Patches that fix this are highly welcome, but probably hard to achieve. Be sure to thoroughly test the sample-app to make sure it really works.

Older versions might have worked at some point, the change to higher minVersion was done around Oct 6, 2021, so you might have some luck with versions from before.
