### ISSUE TITLE
Need donate link!!!

### ISSUE THREAD

**Issue by wH1t3-l0tUs** [centic9/poi-on-android#93]
I don't have too much money for sponsoring, but I really want to thank you. So can you give the link for donation?

**Comment by centic9** [comment]
Thanks for the offer! 

There is a "Sponsor" link on the side-bar in Github, but you can also directly go to https://github.com/sponsors/centic9

I did not create any other way of donating to my projects, but I am open to create other possibilities if you want to suggest a different platform that is easier to use for you.
