### ISSUE TITLE
java.lang.NoSuchMethodError: No static method forArray

### ISSUE THREAD

**Issue by tianbymy** [centic9/poi-on-android#97]
java.lang.NoSuchMethodError: No static method forArray([Ljavax/xml/namespace/QName;)Lorg/apache/xmlbeans/QNameSet; in class Lorg/apache/xmlbeans/QNameSet; or its super classes (declaration of 'org.apache.xmlbeans.QNameSet' appears in base.apk!classes4.dex)

**Comment by tianbymy** [comment]
poi-tl 1.7.3 
poishadow-all 基于master编译

**Comment by centic9** [comment]
Please provide the full stacktrace. 
But it sounds like a mixup of xmlbeans-jar versions, mayba via the poi-tl library... All tools need to use the exact same version of Apache POI and its dependencies.

**Comment by centic9** [comment]
No response, thus closing this for now.
