### ISSUE TITLE
POITextExtractor bug!  docs, xlsx, pptx are OK, but doc file throws Exception!

### ISSUE THREAD

**Issue by bigtang5** [centic9/poi-on-android#98]
try {
            InputStream file = this.getAssets().open("test.doc");
            POITextExtractor extractor = ExtractorFactory.createExtractor(file);
            System.out.println(extractor.getText());
        } catch (IOException e) {
            e.printStackTrace();    //go here!!
        }

shows:   java.io.IOException: Your InputStream was neither an OLE2 stream, nor an OOXML stream or you haven't provide the poi-ooxml*.jar and/or poi-scratchpad*.jar in the classpath/modulepath - FileMagic: OLE2, providers: [org.apache.poi.ooxml.extractor.POIXMLExtractorFactory@aafc2f6]

.xls, .vsd  also have this problem.

**Comment by bigtang5** [comment]
.vsdx failed too, stop at:  extractor.getText(),  not the same bug as .doc.

**Comment by centic9** [comment]
Are you sure you have a valid .doc file at that point? What happens if you try to parse the document fully?

**Comment by centic9** [comment]
After a closer look I found the issue, the shadow-jar did not properly have the service-files merged and thus text-extraction was not available fully for some file-types. 

Should be fixed on master now.
